<!doctype html>
<html lang="nl" class="no-js <?= (is_user_logged_in() ? 'logged-in' : ''); ?>">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover, interactive-widget=overlays-content">

        <!-- Title tag automatically generated by WordPress/Yoast via wp_head() -->

        <?php // Font preloads — start downloading critical fonts before CSS is parsed.
        // These 3 fonts are used above the fold (hero + navigation).
        // crossorigin="anonymous" is REQUIRED for font preloads per spec. ?>
        <link rel="preload" href="<?= THEME_ROOT ;?>/assets/fonts/inter/InterVariable.woff2" as="font" type="font/woff2" crossorigin="anonymous">
        <link rel="preload" href="<?= THEME_ROOT ;?>/assets/fonts/realist-new/Realist-Medium.woff2" as="font" type="font/woff2" crossorigin="anonymous">
        <link rel="preload" href="<?= THEME_ROOT ;?>/assets/fonts/realist-new/Realist-Bold.woff2" as="font" type="font/woff2" crossorigin="anonymous">

        <?php // Inline critical CSS for instant above-the-fold rendering.
        // Contains @font-face for the 3 preloaded fonts — __THEME_FONTS__ placeholder
        // is replaced with the actual theme font URL at output time.
        $critical_css_path = THEME_ROOT_ABS . '/assets/css/nok-critical.min.css';
        if ( ! file_exists( $critical_css_path ) ) {
	        $critical_css_path = THEME_ROOT_ABS . '/assets/css/nok-critical.css';
        }
        if ( file_exists( $critical_css_path ) ) :
	        $critical_css = @file_get_contents( $critical_css_path );
	        if ( $critical_css ) :
		        $critical_css = str_replace( '__THEME_FONTS__', THEME_ROOT . '/assets/fonts', $critical_css );
		        // Strip sourceMappingURL — relative paths break when CSS is inlined into HTML.
		        $critical_css = preg_replace( '#/\*[#@]\s*sourceMappingURL=\S+\s*\*/\s*#', '', $critical_css ); ?>
        <style id="nok-critical-css"><?php echo $critical_css; ?></style>
	        <?php endif;
        endif; ?>

        <?php // Defer non-critical font weights (italic, thin, light, etc.).
        // Critical weights (Inter normal, Realist 400/500/700) are already in critical CSS above.
        $inter_ver   = @filemtime( THEME_ROOT_ABS . '/assets/fonts/inter.css' ) ?: time();
        $realist_ver = @filemtime( THEME_ROOT_ABS . '/assets/fonts/realist.css' ) ?: time(); ?>
        <link href="<?= THEME_ROOT ;?>/assets/fonts/inter.css?ver=<?= $inter_ver; ?>" rel="stylesheet" media="print" onload="this.media='all'" crossorigin="anonymous">
        <noscript><link href="<?= THEME_ROOT ;?>/assets/fonts/inter.css?ver=<?= $inter_ver; ?>" rel="stylesheet" crossorigin="anonymous"></noscript>
        <link href="<?= THEME_ROOT ;?>/assets/fonts/realist.css?ver=<?= $realist_ver; ?>" rel="stylesheet" media="print" onload="this.media='all'" crossorigin="anonymous">
        <noscript><link href="<?= THEME_ROOT ;?>/assets/fonts/realist.css?ver=<?= $realist_ver; ?>" rel="stylesheet" crossorigin="anonymous"></noscript>

        <?php // Cache-busting version for JS entrypoint and all dynamically imported modules.
        // SITE_NONCE is read by DOMule's core.loader to append ?nonce= to dynamic import() URLs.
        $js_cache_ver = @filemtime( THEME_ROOT_ABS . '/assets/js/entrypoint.min.mjs' ) ?: time(); ?>
        <script>const SITE_NONCE = '<?= $js_cache_ver; ?>';</script>
        <link rel="modulepreload" href="<?= THEME_ROOT ;?>/assets/js/entrypoint.min.mjs?ver=<?= $js_cache_ver; ?>">
        <script type="module" src="<?= THEME_ROOT ;?>/assets/js/entrypoint.min.mjs?ver=<?= $js_cache_ver; ?>" defer></script>

        <!-- head data -->
        <?php wp_head(); ?>

    </head>

    <body <?php body_class( 'no-js no-debug nok-bg-body nok-text-contrast' ); ?>>
    <a class="screen-reader-text" href="#main-content"><?php esc_html_e( 'Ga naar inhoud', 'nok' ); ?></a>
    <main id="main-content">